### ISSUE TITLE
Comment: why equal fractions for each county per emm region?

### ISSUE THREAD

**Issue by ahcyip** [dsgrid/dsgrid-project-DECARB#16]
Was browsing how other datasets determined fractions and wondered why the emm region load? was divided into equal fractions for each county? Shouldn't it be scaled (roughly) by population or household?

Asking because I'm wondering if I did my mapping and fractions for transport appropriately.

https://github.com/dsgrid/dsgrid-project-DECARB/blob/577364f5d55112e413f39799bffc760b67ff9dd6/datasets/modeled/buildings/dimension_mappings/emm_region_to_county.csv#L2

**Comment by asatremeloy** [comment]
We decided not to do a more thorough disaggregation (e.g., scaled by population or electricity consumption) because this data is primarily a placeholder and was never really intended to be downscaled from the EMM region to begin with, but given the needs of dsgrid, we decided to do a simple disaggregation where each county in a given EMM region has the same load profile. We are aware of the simplicity of this approach, but the team decided it wasn't worth it to do a more sophisticated downscaling method because these data will be replaced by actual county-level results in the near future.

**Comment by elainethale** [comment]
Fixed in https://github.com/dsgrid/dsgrid-project-DECARB/pull/27
